# basic settings
title: "Pavan Badempet"
email: "pavan9b@gmail.com"
description: "Developer & Entrepreneur"
author: "Pavan Badepet"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%d %B %Y"

# paginations & permalinks
paginate: 9
paginate_path: "/blog/page:num/"
permalink: pretty

# disqus comments
disqus_comments: "no" # yes - show disqus comments, no - hide disqus comments
disqus_shortname: "pavanbadempet" # read more here https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# formsubmit.io
formsubmit_email: "pavan9b@gmail.com" # sign up on https://formsubmit.io/ and confirm your email

# collections
collections:
  - works

# archives

# Disable default plugins to hide Jekyll traces
plugins: []

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

sass:
  style: compressed

markdown:  kramdown